spring:
  application:
    name: rabbitmq-demo
  jackson:
    default-property-inclusion: non_null

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /
    listener:
      simple:
        concurrency: 2
        max-concurrency: 5
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
    queues:
      hello:
        exchange: "${HELLO_EXCHANGE:direct.exchange}"
        queue: "${HELLO_QUEUE:hello.queue}"
        routing-key: "${HELLO_ROUTING_KEY:hello}"
        exchange-type: "direct"
      user:
        exchange: "${USER_EXCHANGE:direct.exchange}"
        queue: "${USER_QUEUE:user.queue}"
        routing-key: "${USER_ROUTING_KEY:user}"
        exchange-type: "topic"
